//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpcommingMovies.Infra.TheMovieDb.I18n {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Expressions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Expressions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpcommingMovies.Infra.TheMovieDb.I18n.Expressions", typeof(Expressions).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server responses with an unexpected result. This could be a temporary issue. Please, try again later..
        /// </summary>
        public static string ParseResponseExceptionFriendlyMessage {
            get {
                return ResourceManager.GetString("ParseResponseExceptionFriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while trying to comunicate to a remote server. This could be a temporary issue. Please, try again later..
        /// </summary>
        public static string RemoteServiceExceptionFriendlyMessage {
            get {
                return ResourceManager.GetString("RemoteServiceExceptionFriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote resource could not be found. This could be a temporary issue. Please, try again later..
        /// </summary>
        public static string ResourceNotFoundExceptionFriendlyMessage {
            get {
                return ResourceManager.GetString("ResourceNotFoundExceptionFriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server says you are not authorized to access the resource..
        /// </summary>
        public static string ResourceUnauthorizedExceptionFriendlyMessage {
            get {
                return ResourceManager.GetString("ResourceUnauthorizedExceptionFriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server reject the request because with a too much requests reason. Please, try again later..
        /// </summary>
        public static string TooManyRequestsExceptionFriendlyMessage {
            get {
                return ResourceManager.GetString("TooManyRequestsExceptionFriendlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds like network connection was closed. This could be a temporary issue. Please, try again later..
        /// </summary>
        public static string TransportExceptionFriendlyMessage {
            get {
                return ResourceManager.GetString("TransportExceptionFriendlyMessage", resourceCulture);
            }
        }
    }
}
